package natsjwt

import (
	"errors"
	"fmt"
	"time"

	"github.com/nats-io/jwt/v2"
	"github.com/nats-io/nkeys"
)

// IssueUserJWT signs a NATS user JWT. The signing key seed authenticates
// the issuer (typically the account NKey or a delegated signing key
// listed in the account JWT). The userPubKey is the public half of a
// fresh user keypair generated by the caller; the device that holds the
// matching private seed can then connect as that user. ttl is added to
// time.Now() to compute the JWT expiry.
//
// Returns the signed JWT string, the JTI assigned by the NATS JWT
// library (a content-derived hash, NOT a random uuid — the library
// computes JTI from the claim hash for tamper-evidence), and the
// absolute expiry time. Callers persist the JTI when they need to
// revoke a JWT before its natural expiry: a stale device JWT is
// detected by comparing its JTI against the platform's record.
//
// Tag keys and values are normalised to lowercase by the underlying
// NATS library; callers that need case sensitivity must encode it in
// the value (e.g. base64 or a separator scheme).
func IssueUserJWT(signingKeySeed string, userPubKey string, claims UserClaims, ttl time.Duration) (string, string, time.Time, error) {
	if signingKeySeed == "" {
		return "", "", time.Time{}, errors.New("natsjwt: signing key seed is empty")
	}
	if userPubKey == "" {
		return "", "", time.Time{}, errors.New("natsjwt: user public key is empty")
	}

	signingKP, err := nkeys.FromSeed([]byte(signingKeySeed))
	if err != nil {
		return "", "", time.Time{}, fmt.Errorf("natsjwt: parse signing seed: %w", err)
	}

	uc := jwt.NewUserClaims(userPubKey)
	uc.Name = claims.Name
	// In bearer mode the leaf skips the nonce-signing challenge — the
	// JWT alone authenticates the connection. Required for MQTT devices
	// whose firmware cannot perform Ed25519 signing on the CONNECT path.
	uc.BearerToken = claims.BearerToken
	// Truncate expiry to second precision so callers' returned value
	// matches what a downstream ParseUserJWT will read back. The JWT
	// "exp" claim is encoded as a Unix-seconds integer.
	expiresAt := time.Now().Add(ttl).UTC().Truncate(time.Second)
	uc.Expires = expiresAt.Unix()

	if claims.Tags != nil {
		for k, v := range claims.Tags {
			uc.Tags.Add(k + ":" + v)
		}
	}

	for _, subject := range claims.Pub.Allow {
		uc.Pub.Allow.Add(subject)
	}
	for _, subject := range claims.Pub.Deny {
		uc.Pub.Deny.Add(subject)
	}
	for _, subject := range claims.Sub.Allow {
		uc.Sub.Allow.Add(subject)
	}
	for _, subject := range claims.Sub.Deny {
		uc.Sub.Deny.Add(subject)
	}

	token, err := uc.Encode(signingKP)
	if err != nil {
		return "", "", time.Time{}, fmt.Errorf("natsjwt: encode user jwt: %w", err)
	}

	// nats-jwt overwrites the ID claim with a content-derived hash
	// during Encode. Decode the freshly-signed JWT to read the JTI
	// the library actually assigned so callers can persist it for
	// revocation tracking.
	parsed, err := jwt.DecodeUserClaims(token)
	if err != nil {
		return "", "", time.Time{}, fmt.Errorf("natsjwt: read assigned jti: %w", err)
	}
	return token, parsed.ID, expiresAt, nil
}

// ParseUserJWT decodes a JWT and returns its claim subset. The function
// does NOT verify the signature against an issuer — that is the leaf's
// job at MQTT CONNECT time and the HTTP middleware's job for refresh
// requests. Callers that need verification should layer it on top of
// this read; callers that have already trusted the bearer can call
// this for the claims directly.
func ParseUserJWT(jwtToken string) (UserClaims, string, time.Time, error) {
	if jwtToken == "" {
		return UserClaims{}, "", time.Time{}, errors.New("natsjwt: jwt token is empty")
	}

	uc, err := jwt.DecodeUserClaims(jwtToken)
	if err != nil {
		return UserClaims{}, "", time.Time{}, fmt.Errorf("natsjwt: decode user jwt: %w", err)
	}

	out := UserClaims{
		Name:        uc.Name,
		Issuer:      uc.Issuer,
		BearerToken: uc.BearerToken,
		Tags:        make(map[string]string, len(uc.Tags)),
		Pub: PermissionList{
			Allow: append([]string(nil), uc.Pub.Allow...),
			Deny:  append([]string(nil), uc.Pub.Deny...),
		},
		Sub: PermissionList{
			Allow: append([]string(nil), uc.Sub.Allow...),
			Deny:  append([]string(nil), uc.Sub.Deny...),
		},
	}
	for _, raw := range uc.Tags {
		if k, v, ok := splitTag(raw); ok {
			out.Tags[k] = v
		}
	}

	expiresAt := time.Unix(uc.Expires, 0).UTC()
	return out, uc.ID, expiresAt, nil
}

// splitTag parses a "key:value" tag. NATS stores Tags as a flat slice
// of strings; the convention this package uses is colon-separated kv,
// matching what the Synadia tooling and most platforms do.
func splitTag(raw string) (string, string, bool) {
	for i := 0; i < len(raw); i++ {
		if raw[i] == ':' {
			return raw[:i], raw[i+1:], true
		}
	}
	return "", "", false
}
